name: smart_queue
description: Lightweight job queue for Dart/Flutter. Handles offline tasks, retries, persistence.
version: 0.0.1
homepage: https://github.com/muhammadwaqasdev/smart_queue
repository: https://github.com/muhammadwaqasdev/smart_queue
issue_tracker: https://github.com/muhammadwaqasdev/smart_queue/issues
topics:
  - queue
  - background
  - offline
  - retry
  - hive

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.18.0
  hive: ^2.2.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
